apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-deployment
  namespace: project-production
  labels:
    type: database
    instance: mongo

spec:
  template:
    metadata:
      name: mongo-pod
      namespace: project-production
      labels:
        type: database
        instance: mongo

    spec:
      containers:
        - name: mongo-container
          image: mongo:latest
          envFrom:
            - configMapRef:
                name: mongo-configmap
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc

  replicas: 1
  selector:
    matchLabels:
      type: database
      instance: mongo
