apiVersion: v1
kind: Service

metadata:
  name: express-clusterip
  namespace: project-production
spec:
  type: ClusterIP
  ports:
    - name: express-port
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    type: backend
    instance: express
