apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-production-pv

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/production/db"
  # claimRef:
  #   name: mongo-pvc
  #   namespace: project-production
