apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-development-pv

spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/development/db"
  claimRef:
    name: mongo-pvc
    namespace: project-development
