apiVersion: v1
kind: Service

metadata:
  name: mongo-clusterip
  namespace: project-development
spec:
  type: ClusterIP
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    type: database
    instance: mongo
