apiVersion: v1
kind: Service

metadata:
  name: react-clusterip
  namespace: project-development
spec:
  type: ClusterIP
  ports:
    - name: react-port
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    type: frontend
    instance: react
