apiVersion: v1
kind: Service

metadata:
  name: redis-clusterip
  namespace: project-development
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    type: database
    instance: redis
